### ISSUE TITLE
Sprint 1 Goals:

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/pib-cli#613]
Customer Support:
- [x] WMT
  - ~KiC HoL #280 (slipped - customer)~
- [x]  KFC
   - [x] Failover design #590
- [x]  McD/AD

In-Person Support/Demo:
- [x]  McD EBC #281
   - [x] Modify .net w/KV #535
   - [x] Arc - GO ext #491
   - [x] Arc KV ext #489
   - [x] Arc Demo #213

-------------------------------------------

PG Transition:
- [x] Grafana Sub/PG #204
- [x] Groups GH/MS #486
- [x] Demo Env #205
- [x]  Align trackers #573
- [x] create pib-dev #575

-------------------------------------------
EngFun:
- [x] Delete Repo #1 (INDIA)
- [x] Repo Cleanup/Plan #438
- [x] Finalize MVP scope #488
-------------------------------------------
PiB MVP 

Technical Debt:
- [x] gitops-template #540
- [x] latest docker image #507, #508
- [x] Consolidate pib-webv #501
- [x] Consolidate VOE fleet #485

Bugs:
- [x] GitOps Auto #519

CLI:
- [x] CLI  #487

DevExp:
- ~App-new #444 (pushed to S2)~
- [x] voe-app GH #478
