### ISSUE TITLE
Release Checklist - DRAFT

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/pib-cli#649]
## Release Summary

- Title / Repo
- vx.x.x

### Validation

- [ ] All packages up to date (or task created)
- [ ] Remove any unused flags or conditional compilation
- [ ] Remove unused packages
- [ ] Code Version updated
- [ ] Code Review completed
- [ ] All existing automated tests (unit and e2e) pass successfully, new tests added as needed
- [ ] Code changes checked into main
- [ ] Sync github actions from main template
- [ ] Existing documentation is updated (readme, .md's)
- [ ] New documentation needed to support the change is created
- [ ] CI completes successfully
- [ ] CD completes successfully
- [ ] Smoke test deployed for 48 hours

### Release

- [ ] Reviewed & updated readme for Developer Experience
- [ ] Resolve to-do from code
- [ ] Verify all new libraries and dependencies are customer approved
- [ ] Tag repo with version tag
- [ ] Ensure CI-CD runs correctly
- [ ] Ran cred sc
